/**
 * Created by Sergey Krivorotov.
 *
 * Contains constants for callout method.
 */

public with sharing class CalloutMethodConstants {
    public static final String GET_METHOD = 'GET';
    public static final String HEAD_METHOD = 'HEAD';
    public static final String POST_METHOD = 'POST';
    public static final String PUT_METHOD = 'PUT';
    public static final String DELETE_METHOD = 'DELETE';
    public static final String CONNECT_METHOD = 'CONNECT';
    public static final String OPTIONS_METHOD = 'OPTIONS';
    public static final String TRACE_METHOD = 'TRACE';
    public static final String PATCH_METHOD = 'PATCH';

}